const ACTION_TYPE = {
  GET_MESSAGES_ACTION: 'GET_MESSAGES_ACTION',
  GET_MESSAGES_REQUEST: 'GET_MESSAGES_REQUEST',
  GET_MESSAGES_REQUEST_SUCCESS: 'GET_MESSAGES_REQUEST_SUCCESS',
  GET_MESSAGES_REQUEST_ERROR: 'GET_MESSAGES_REQUEST_ERROR',

  SEND_MESSAGE_ACTION: 'SEND_MESSAGE_ACTION',
  SEND_MESSAGE_ERROR_ACTION: 'SEND_MESSAGE_ERROR_ACTION',

  NEW_MESSAGE_ACTION: 'NEW_MESSAGE_ACTION',
};

export default ACTION_TYPE;
